/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISomniaAgentPlatform,
  ISomniaAgentPlatformInterface,
} from "../../../contracts/AionisAgentManager.sol/ISomniaAgentPlatform";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "cbContract",
        type: "address",
      },
      {
        internalType: "bytes4",
        name: "cbSelector",
        type: "bytes4",
      },
    ],
    name: "createRequest",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ISomniaAgentPlatform__factory {
  static readonly abi = _abi;
  static createInterface(): ISomniaAgentPlatformInterface {
    return new Interface(_abi) as ISomniaAgentPlatformInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISomniaAgentPlatform {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISomniaAgentPlatform;
  }
}
