/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FollowerRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createVault"
      | "follow"
      | "followIndex"
      | "followers"
      | "following"
      | "getFollowers"
      | "getFollowing"
      | "getVault"
      | "isFollowing"
      | "resetVault"
      | "unfollow"
      | "vaults"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Followed"
      | "Unfollowed"
      | "VaultCreated"
      | "VaultReset"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createVault",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "follow", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "followIndex",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "followers",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "following",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFollowers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFollowing",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isFollowing",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resetVault",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unfollow",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vaults", values: [AddressLike]): string;

  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "follow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "followIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "followers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "following", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFollowers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFollowing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isFollowing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resetVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unfollow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;
}

export namespace FollowedEvent {
  export type InputTuple = [follower: AddressLike, leader: AddressLike];
  export type OutputTuple = [follower: string, leader: string];
  export interface OutputObject {
    follower: string;
    leader: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnfollowedEvent {
  export type InputTuple = [follower: AddressLike, leader: AddressLike];
  export type OutputTuple = [follower: string, leader: string];
  export interface OutputObject {
    follower: string;
    leader: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultCreatedEvent {
  export type InputTuple = [user: AddressLike, virtualUsdc: BigNumberish];
  export type OutputTuple = [user: string, virtualUsdc: bigint];
  export interface OutputObject {
    user: string;
    virtualUsdc: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultResetEvent {
  export type InputTuple = [user: AddressLike, virtualUsdc: BigNumberish];
  export type OutputTuple = [user: string, virtualUsdc: bigint];
  export interface OutputObject {
    user: string;
    virtualUsdc: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FollowerRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): FollowerRegistry;
  waitForDeployment(): Promise<this>;

  interface: FollowerRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createVault: TypedContractMethod<
    [virtualUsdc: BigNumberish],
    [void],
    "nonpayable"
  >;

  follow: TypedContractMethod<[leader: AddressLike], [void], "nonpayable">;

  followIndex: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  followers: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  following: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFollowers: TypedContractMethod<[leader: AddressLike], [string[]], "view">;

  getFollowing: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  getVault: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, boolean] & {
        virtualUsdc: bigint;
        startingCapital: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  isFollowing: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  resetVault: TypedContractMethod<
    [virtualUsdc: BigNumberish],
    [void],
    "nonpayable"
  >;

  unfollow: TypedContractMethod<[leader: AddressLike], [void], "nonpayable">;

  vaults: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean] & {
        virtualUsdc: bigint;
        startingCapital: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createVault"
  ): TypedContractMethod<[virtualUsdc: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "follow"
  ): TypedContractMethod<[leader: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "followIndex"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "followers"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "following"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFollowers"
  ): TypedContractMethod<[leader: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getFollowing"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVault"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, boolean] & {
        virtualUsdc: bigint;
        startingCapital: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isFollowing"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "resetVault"
  ): TypedContractMethod<[virtualUsdc: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unfollow"
  ): TypedContractMethod<[leader: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vaults"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean] & {
        virtualUsdc: bigint;
        startingCapital: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "Followed"
  ): TypedContractEvent<
    FollowedEvent.InputTuple,
    FollowedEvent.OutputTuple,
    FollowedEvent.OutputObject
  >;
  getEvent(
    key: "Unfollowed"
  ): TypedContractEvent<
    UnfollowedEvent.InputTuple,
    UnfollowedEvent.OutputTuple,
    UnfollowedEvent.OutputObject
  >;
  getEvent(
    key: "VaultCreated"
  ): TypedContractEvent<
    VaultCreatedEvent.InputTuple,
    VaultCreatedEvent.OutputTuple,
    VaultCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultReset"
  ): TypedContractEvent<
    VaultResetEvent.InputTuple,
    VaultResetEvent.OutputTuple,
    VaultResetEvent.OutputObject
  >;

  filters: {
    "Followed(address,address)": TypedContractEvent<
      FollowedEvent.InputTuple,
      FollowedEvent.OutputTuple,
      FollowedEvent.OutputObject
    >;
    Followed: TypedContractEvent<
      FollowedEvent.InputTuple,
      FollowedEvent.OutputTuple,
      FollowedEvent.OutputObject
    >;

    "Unfollowed(address,address)": TypedContractEvent<
      UnfollowedEvent.InputTuple,
      UnfollowedEvent.OutputTuple,
      UnfollowedEvent.OutputObject
    >;
    Unfollowed: TypedContractEvent<
      UnfollowedEvent.InputTuple,
      UnfollowedEvent.OutputTuple,
      UnfollowedEvent.OutputObject
    >;

    "VaultCreated(address,uint256)": TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
    VaultCreated: TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;

    "VaultReset(address,uint256)": TypedContractEvent<
      VaultResetEvent.InputTuple,
      VaultResetEvent.OutputTuple,
      VaultResetEvent.OutputObject
    >;
    VaultReset: TypedContractEvent<
      VaultResetEvent.InputTuple,
      VaultResetEvent.OutputTuple,
      VaultResetEvent.OutputObject
    >;
  };
}
