/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AionisAgentManager {
  export type FollowerProfileStruct = {
    leader: AddressLike;
    riskTolerance: BigNumberish;
    maxAllocationUsdc: BigNumberish;
    depositedUsdc: BigNumberish;
    active: boolean;
    openPositionWsomi: BigNumberish;
  };

  export type FollowerProfileStructOutput = [
    leader: string,
    riskTolerance: bigint,
    maxAllocationUsdc: bigint,
    depositedUsdc: bigint,
    active: boolean,
    openPositionWsomi: bigint
  ] & {
    leader: string;
    riskTolerance: bigint;
    maxAllocationUsdc: bigint;
    depositedUsdc: bigint;
    active: boolean;
    openPositionWsomi: bigint;
  };
}

export interface AionisAgentManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AGENT_PLATFORM"
      | "AIONIS_API"
      | "JSON_API_AGENT_ID"
      | "LLM_AGENT_ID"
      | "MAX_TRADE_AGE"
      | "MIN_EXECUTE_SCORE"
      | "QUICKSWAP_ROUTER"
      | "USDCE"
      | "WSOMI"
      | "activeRequest"
      | "checkLeaderActivity"
      | "deposit"
      | "getProfile"
      | "getRequestStage"
      | "onStrategistResponse"
      | "onWatcherResponse"
      | "pendingRequests"
      | "profiles"
      | "startFollowing"
      | "stopFollowing"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CopyTradeExecuted"
      | "CopyTradeSkipped"
      | "FollowingStarted"
      | "FollowingStopped"
      | "FundsDeposited"
      | "FundsWithdrawn"
      | "StrategistRequestSent"
      | "StrategistResponseReceived"
      | "WatcherRequestSent"
      | "WatcherResponseReceived"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AGENT_PLATFORM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "AIONIS_API",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "JSON_API_AGENT_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LLM_AGENT_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_TRADE_AGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_EXECUTE_SCORE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "QUICKSWAP_ROUTER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDCE", values?: undefined): string;
  encodeFunctionData(functionFragment: "WSOMI", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "activeRequest",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkLeaderActivity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestStage",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onStrategistResponse",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onWatcherResponse",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRequests",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "profiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startFollowing",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stopFollowing",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "AGENT_PLATFORM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "AIONIS_API", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "JSON_API_AGENT_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LLM_AGENT_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_TRADE_AGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_EXECUTE_SCORE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "QUICKSWAP_ROUTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDCE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WSOMI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "activeRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkLeaderActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRequestStage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onStrategistResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onWatcherResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "profiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startFollowing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stopFollowing",
    data: BytesLike
  ): Result;
}

export namespace CopyTradeExecutedEvent {
  export type InputTuple = [
    follower: AddressLike,
    leader: AddressLike,
    usdcSpent: BigNumberish,
    wsomiReceived: BigNumberish,
    copyScore: BigNumberish
  ];
  export type OutputTuple = [
    follower: string,
    leader: string,
    usdcSpent: bigint,
    wsomiReceived: bigint,
    copyScore: bigint
  ];
  export interface OutputObject {
    follower: string;
    leader: string;
    usdcSpent: bigint;
    wsomiReceived: bigint;
    copyScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CopyTradeSkippedEvent {
  export type InputTuple = [
    follower: AddressLike,
    leader: AddressLike,
    copyScore: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    follower: string,
    leader: string,
    copyScore: bigint,
    reason: string
  ];
  export interface OutputObject {
    follower: string;
    leader: string;
    copyScore: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FollowingStartedEvent {
  export type InputTuple = [
    follower: AddressLike,
    leader: AddressLike,
    riskTolerance: BigNumberish,
    maxAllocationUsdc: BigNumberish
  ];
  export type OutputTuple = [
    follower: string,
    leader: string,
    riskTolerance: bigint,
    maxAllocationUsdc: bigint
  ];
  export interface OutputObject {
    follower: string;
    leader: string;
    riskTolerance: bigint;
    maxAllocationUsdc: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FollowingStoppedEvent {
  export type InputTuple = [follower: AddressLike, leader: AddressLike];
  export type OutputTuple = [follower: string, leader: string];
  export interface OutputObject {
    follower: string;
    leader: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsDepositedEvent {
  export type InputTuple = [follower: AddressLike, amount: BigNumberish];
  export type OutputTuple = [follower: string, amount: bigint];
  export interface OutputObject {
    follower: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [follower: AddressLike, amount: BigNumberish];
  export type OutputTuple = [follower: string, amount: bigint];
  export interface OutputObject {
    follower: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategistRequestSentEvent {
  export type InputTuple = [
    requestId: BytesLike,
    follower: AddressLike,
    prompt: string
  ];
  export type OutputTuple = [
    requestId: string,
    follower: string,
    prompt: string
  ];
  export interface OutputObject {
    requestId: string;
    follower: string;
    prompt: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategistResponseReceivedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    follower: AddressLike,
    copyScore: BigNumberish,
    willExecute: boolean
  ];
  export type OutputTuple = [
    requestId: string,
    follower: string,
    copyScore: bigint,
    willExecute: boolean
  ];
  export interface OutputObject {
    requestId: string;
    follower: string;
    copyScore: bigint;
    willExecute: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WatcherRequestSentEvent {
  export type InputTuple = [
    requestId: BytesLike,
    follower: AddressLike,
    leader: AddressLike
  ];
  export type OutputTuple = [
    requestId: string,
    follower: string,
    leader: string
  ];
  export interface OutputObject {
    requestId: string;
    follower: string;
    leader: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WatcherResponseReceivedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    tokenIn: AddressLike,
    tokenOut: AddressLike,
    amountIn: BigNumberish,
    tradeTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    tradeTimestamp: bigint
  ];
  export interface OutputObject {
    requestId: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    tradeTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AionisAgentManager extends BaseContract {
  connect(runner?: ContractRunner | null): AionisAgentManager;
  waitForDeployment(): Promise<this>;

  interface: AionisAgentManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AGENT_PLATFORM: TypedContractMethod<[], [string], "view">;

  AIONIS_API: TypedContractMethod<[], [string], "view">;

  JSON_API_AGENT_ID: TypedContractMethod<[], [bigint], "view">;

  LLM_AGENT_ID: TypedContractMethod<[], [bigint], "view">;

  MAX_TRADE_AGE: TypedContractMethod<[], [bigint], "view">;

  MIN_EXECUTE_SCORE: TypedContractMethod<[], [bigint], "view">;

  QUICKSWAP_ROUTER: TypedContractMethod<[], [string], "view">;

  USDCE: TypedContractMethod<[], [string], "view">;

  WSOMI: TypedContractMethod<[], [string], "view">;

  activeRequest: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  checkLeaderActivity: TypedContractMethod<
    [follower: AddressLike],
    [void],
    "payable"
  >;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getProfile: TypedContractMethod<
    [follower: AddressLike],
    [AionisAgentManager.FollowerProfileStructOutput],
    "view"
  >;

  getRequestStage: TypedContractMethod<
    [follower: AddressLike],
    [[bigint, string] & { stage: bigint; requestId: string }],
    "view"
  >;

  onStrategistResponse: TypedContractMethod<
    [requestId: BytesLike, response: BytesLike],
    [void],
    "nonpayable"
  >;

  onWatcherResponse: TypedContractMethod<
    [requestId: BytesLike, response: BytesLike],
    [void],
    "nonpayable"
  >;

  pendingRequests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint] & {
        follower: string;
        leader: string;
        tradeData: string;
        stage: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  profiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean, bigint] & {
        leader: string;
        riskTolerance: bigint;
        maxAllocationUsdc: bigint;
        depositedUsdc: bigint;
        active: boolean;
        openPositionWsomi: bigint;
      }
    ],
    "view"
  >;

  startFollowing: TypedContractMethod<
    [
      leader: AddressLike,
      riskTolerance: BigNumberish,
      maxAllocationUsdc: BigNumberish,
      initialDeposit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  stopFollowing: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AGENT_PLATFORM"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "AIONIS_API"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "JSON_API_AGENT_ID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LLM_AGENT_ID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_TRADE_AGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_EXECUTE_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "QUICKSWAP_ROUTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDCE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WSOMI"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activeRequest"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "checkLeaderActivity"
  ): TypedContractMethod<[follower: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getProfile"
  ): TypedContractMethod<
    [follower: AddressLike],
    [AionisAgentManager.FollowerProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRequestStage"
  ): TypedContractMethod<
    [follower: AddressLike],
    [[bigint, string] & { stage: bigint; requestId: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "onStrategistResponse"
  ): TypedContractMethod<
    [requestId: BytesLike, response: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onWatcherResponse"
  ): TypedContractMethod<
    [requestId: BytesLike, response: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pendingRequests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint] & {
        follower: string;
        leader: string;
        tradeData: string;
        stage: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "profiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean, bigint] & {
        leader: string;
        riskTolerance: bigint;
        maxAllocationUsdc: bigint;
        depositedUsdc: bigint;
        active: boolean;
        openPositionWsomi: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "startFollowing"
  ): TypedContractMethod<
    [
      leader: AddressLike,
      riskTolerance: BigNumberish,
      maxAllocationUsdc: BigNumberish,
      initialDeposit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stopFollowing"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CopyTradeExecuted"
  ): TypedContractEvent<
    CopyTradeExecutedEvent.InputTuple,
    CopyTradeExecutedEvent.OutputTuple,
    CopyTradeExecutedEvent.OutputObject
  >;
  getEvent(
    key: "CopyTradeSkipped"
  ): TypedContractEvent<
    CopyTradeSkippedEvent.InputTuple,
    CopyTradeSkippedEvent.OutputTuple,
    CopyTradeSkippedEvent.OutputObject
  >;
  getEvent(
    key: "FollowingStarted"
  ): TypedContractEvent<
    FollowingStartedEvent.InputTuple,
    FollowingStartedEvent.OutputTuple,
    FollowingStartedEvent.OutputObject
  >;
  getEvent(
    key: "FollowingStopped"
  ): TypedContractEvent<
    FollowingStoppedEvent.InputTuple,
    FollowingStoppedEvent.OutputTuple,
    FollowingStoppedEvent.OutputObject
  >;
  getEvent(
    key: "FundsDeposited"
  ): TypedContractEvent<
    FundsDepositedEvent.InputTuple,
    FundsDepositedEvent.OutputTuple,
    FundsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "StrategistRequestSent"
  ): TypedContractEvent<
    StrategistRequestSentEvent.InputTuple,
    StrategistRequestSentEvent.OutputTuple,
    StrategistRequestSentEvent.OutputObject
  >;
  getEvent(
    key: "StrategistResponseReceived"
  ): TypedContractEvent<
    StrategistResponseReceivedEvent.InputTuple,
    StrategistResponseReceivedEvent.OutputTuple,
    StrategistResponseReceivedEvent.OutputObject
  >;
  getEvent(
    key: "WatcherRequestSent"
  ): TypedContractEvent<
    WatcherRequestSentEvent.InputTuple,
    WatcherRequestSentEvent.OutputTuple,
    WatcherRequestSentEvent.OutputObject
  >;
  getEvent(
    key: "WatcherResponseReceived"
  ): TypedContractEvent<
    WatcherResponseReceivedEvent.InputTuple,
    WatcherResponseReceivedEvent.OutputTuple,
    WatcherResponseReceivedEvent.OutputObject
  >;

  filters: {
    "CopyTradeExecuted(address,address,uint256,uint256,uint8)": TypedContractEvent<
      CopyTradeExecutedEvent.InputTuple,
      CopyTradeExecutedEvent.OutputTuple,
      CopyTradeExecutedEvent.OutputObject
    >;
    CopyTradeExecuted: TypedContractEvent<
      CopyTradeExecutedEvent.InputTuple,
      CopyTradeExecutedEvent.OutputTuple,
      CopyTradeExecutedEvent.OutputObject
    >;

    "CopyTradeSkipped(address,address,uint8,string)": TypedContractEvent<
      CopyTradeSkippedEvent.InputTuple,
      CopyTradeSkippedEvent.OutputTuple,
      CopyTradeSkippedEvent.OutputObject
    >;
    CopyTradeSkipped: TypedContractEvent<
      CopyTradeSkippedEvent.InputTuple,
      CopyTradeSkippedEvent.OutputTuple,
      CopyTradeSkippedEvent.OutputObject
    >;

    "FollowingStarted(address,address,uint8,uint256)": TypedContractEvent<
      FollowingStartedEvent.InputTuple,
      FollowingStartedEvent.OutputTuple,
      FollowingStartedEvent.OutputObject
    >;
    FollowingStarted: TypedContractEvent<
      FollowingStartedEvent.InputTuple,
      FollowingStartedEvent.OutputTuple,
      FollowingStartedEvent.OutputObject
    >;

    "FollowingStopped(address,address)": TypedContractEvent<
      FollowingStoppedEvent.InputTuple,
      FollowingStoppedEvent.OutputTuple,
      FollowingStoppedEvent.OutputObject
    >;
    FollowingStopped: TypedContractEvent<
      FollowingStoppedEvent.InputTuple,
      FollowingStoppedEvent.OutputTuple,
      FollowingStoppedEvent.OutputObject
    >;

    "FundsDeposited(address,uint256)": TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;
    FundsDeposited: TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;

    "FundsWithdrawn(address,uint256)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "StrategistRequestSent(bytes32,address,string)": TypedContractEvent<
      StrategistRequestSentEvent.InputTuple,
      StrategistRequestSentEvent.OutputTuple,
      StrategistRequestSentEvent.OutputObject
    >;
    StrategistRequestSent: TypedContractEvent<
      StrategistRequestSentEvent.InputTuple,
      StrategistRequestSentEvent.OutputTuple,
      StrategistRequestSentEvent.OutputObject
    >;

    "StrategistResponseReceived(bytes32,address,uint8,bool)": TypedContractEvent<
      StrategistResponseReceivedEvent.InputTuple,
      StrategistResponseReceivedEvent.OutputTuple,
      StrategistResponseReceivedEvent.OutputObject
    >;
    StrategistResponseReceived: TypedContractEvent<
      StrategistResponseReceivedEvent.InputTuple,
      StrategistResponseReceivedEvent.OutputTuple,
      StrategistResponseReceivedEvent.OutputObject
    >;

    "WatcherRequestSent(bytes32,address,address)": TypedContractEvent<
      WatcherRequestSentEvent.InputTuple,
      WatcherRequestSentEvent.OutputTuple,
      WatcherRequestSentEvent.OutputObject
    >;
    WatcherRequestSent: TypedContractEvent<
      WatcherRequestSentEvent.InputTuple,
      WatcherRequestSentEvent.OutputTuple,
      WatcherRequestSentEvent.OutputObject
    >;

    "WatcherResponseReceived(bytes32,address,address,uint256,uint256)": TypedContractEvent<
      WatcherResponseReceivedEvent.InputTuple,
      WatcherResponseReceivedEvent.OutputTuple,
      WatcherResponseReceivedEvent.OutputObject
    >;
    WatcherResponseReceived: TypedContractEvent<
      WatcherResponseReceivedEvent.InputTuple,
      WatcherResponseReceivedEvent.OutputTuple,
      WatcherResponseReceivedEvent.OutputObject
    >;
  };
}
