/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ISomniaAgentPlatformInterface extends Interface {
  getFunction(nameOrSignature: "createRequest"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createRequest",
    values: [BigNumberish, BytesLike, AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createRequest",
    data: BytesLike
  ): Result;
}

export interface ISomniaAgentPlatform extends BaseContract {
  connect(runner?: ContractRunner | null): ISomniaAgentPlatform;
  waitForDeployment(): Promise<this>;

  interface: ISomniaAgentPlatformInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createRequest: TypedContractMethod<
    [
      agentId: BigNumberish,
      data: BytesLike,
      cbContract: AddressLike,
      cbSelector: BytesLike
    ],
    [string],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createRequest"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      data: BytesLike,
      cbContract: AddressLike,
      cbSelector: BytesLike
    ],
    [string],
    "payable"
  >;

  filters: {};
}
