/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILLMAgent,
  ILLMAgentInterface,
} from "../../../contracts/VaultManager.sol/ILLMAgent";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "prompt",
        type: "string",
      },
      {
        internalType: "string",
        name: "system",
        type: "string",
      },
      {
        internalType: "int256",
        name: "minValue",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "maxValue",
        type: "int256",
      },
      {
        internalType: "bool",
        name: "chainOfThought",
        type: "bool",
      },
    ],
    name: "inferNumber",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILLMAgent__factory {
  static readonly abi = _abi;
  static createInterface(): ILLMAgentInterface {
    return new Interface(_abi) as ILLMAgentInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ILLMAgent {
    return new Contract(address, _abi, runner) as unknown as ILLMAgent;
  }
}
