/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISomniaAgentPlatform } from "./ISomniaAgentPlatform";
export type { IaUSD } from "./IaUSD";
export type { VaultManager } from "./VaultManager";
